/*
 * Copyright (c) 2013 Qualcomm Atheros, Inc.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA. 
 *
 */ 

#ifndef _ETH_RX_DBG_H_
#define _ETH_RX_DBG_H_

#define  MAX_NUM_MARKERS  4
#define  MAX_NUM_STREAMS  4

/* Structure to hold marker information
 */
struct marker_info {
    u_int16_t  offset;     /* Marker offset in bytes wrt start of the wbuf     */
	u_int16_t  num_bytes;  /* Width of the marker field in bytes - max 4 bytes */
    u_int32_t  match;      /* Marker pattern match value- used as packet filter */
};

/* Video debug structure 
 * Used to hold marker, rx sequence number & timestamp information
 */ 
struct eth_dbg {
	/* Marker information per stream */                       
    struct     marker_info markers[MAX_NUM_STREAMS][MAX_NUM_MARKERS];
	u_int16_t  rxseq_offset;    /* Pkt seq number offset in bytes wrt wbuf start        */
	u_int16_t  rxseq_num_bytes; /* Number of bytes that make up the pkt seq num field   */
	u_int16_t  time_offset;     /* Pkt timestamp offset in bytes wrt wbuf start         */   
	u_int16_t  time_num_bytes;	/* Number of bytes that make up the pkt timestamp field */
};

/* Video debug parameters - set using ethdebug program 
 * These parameters are used to provide the user with an interface to set markers for filtering
 * received packets & finding the locations of the rxsequence numbers/timestamps within the wbuf
 * The markers can be used to look for signatures of pkts generated by standard test tools like
 * chariot/iperf. These marker fields can be extracted from the wbuf by looking at the offset wrt
 * the start of the wbuf & extracting the number of bytes that correspond to this marker. The
 * extracted marker can then be compared with a matching pattern & filtered appropriately.
 * The rx sequence number & timetamp can also be extracted from the wbuf by looking at the offset 
 * wrt the start of the wbuf & extracting the number of bytes that correspond to the rx seq num &
 * timestamp respectively. These can be used to detect pkt losses and for jitter measurements
 */ 
struct eth_dbg_params {
	u_int32_t vi_dbg_cfg;            /* Video debug configuration - Bit0- enable dbg */
	u_int8_t  vi_num_streams;        /* Number of streams */
	u_int8_t  vi_stream_num;         /* the stream number whose markers are being set */
    u_int8_t  vi_num_markers;        /* total number of markers used to filter pkts */   
    u_int8_t  vi_marker_num;         /* the marker number whose parameters (offset, size & match) are being set */
    u_int32_t vi_marker_offset_size; /* byte offset from skb start (upper 16 bits) & size in bytes(lower 16 bits) */
    u_int32_t vi_marker_match;       /* marker pattern match used in filtering */
    u_int32_t vi_rxseq_offset_size;  /* Rx Seq num offset skb start (upper 16 bits) & size in bytes(lower 16 bits) */
	u_int32_t vi_rx_seq_rshift;      /* right-shift value in case field is not word aligned */
	u_int32_t vi_rx_seq_max;         /* Max Rx seq number */ 
	u_int32_t vi_rx_seq_drop;        /* Indicator to the debug app that a particular seq num has been dropped */ 
	u_int32_t vi_time_offset_size;   /* Timestamp offset skb start (upper 16 bits) & size in bytes(lower 16 bits) */
    u_int32_t vi_dbg_restart;        /* set to 1 to re-initialize counters/parameters */   
    struct eth_dbg vi_dbg;
};

#endif
