#!/bin/sh
##################################################################################
## configure_vlanvap
##
## shell function to configure the vap for vlan
## arguments
##   $1 - $APNAME - name of the interface eg. ath0
##   $2 - $BRNAME - name of the bridge eg. br2
##   $3 - $VLANID - Id of the VLAN, eg 2
##   $4 - $SECMODE - Security mode like WPA
##   $5 - $SECFILE - like 8021x.conf
## call as
##     configure_vlanvap ath0 br2 2 WPA wpa2EAP.conf
##
configure_vlanvap() {
        VAPNAME=$1
        VBRNAME=$2
        VVLANID=$3
        VSECMODE=$4
        VSECFILE=$5
        VIPADDR=$6
        #verify sec args 
        if [ "${VSECMODE}" != "None" ]; then
            if [ ${VSECFILE} = "None" ]; then
                echo "No security file specified for $VSECMODE on $VAPNAME"
                exit 1
            fi
        fi
        #add tags on both WAN, LAN and athx
        VESSID=`iwconfig ${VAPNAME} | grep ESSID | cut -f2 -d\"`
        brctl addbr $VBRNAME
        brctl delif br0 $VAPNAME
        vconfig add $VAPNAME $VVLANID
        vconfig add WAN $VVLANID
        vconfig add LAN $VVLANID
        brctl addif $VBRNAME $VAPNAME.$VVLANID
        brctl addif $VBRNAME WAN.$VVLANID
        brctl addif $VBRNAME LAN.$VVLANID
        ifconfig $VAPNAME.$VVLANID up
        ifconfig WAN.$VVLANID up
        ifconfig LAN.$VVLANID up
        ifconfig $VBRNAME $VIPADDR up

        ##
        ## Add a gratutious ARP after the bridge is up to ensure
        ## "Everybody knows your name"
        ##

        if [ "_$VIPADDR" != "_" ]; then
            arping -U -c 1 -I ${VBRNAME} $VIPADDR
        fi

        ##
        ## If hostapd or topology needs to know about this, lets create
        ## a bridge record
        ##

        if [ "${VSECMODE}" != "WEP" -a "${VSECMODE}" != "None" ]; then
            echo -e "\tinterface $VAPNAME" >> /tmp/bc$VVLANID
        fi
} 
#end configure_vlanvap

#####################################################################################
##
## "check_instance" procedure
##
## check the input shell script is running or not
## arguments
## $1 - $FILENAME - the file name with full path 
##

check_instance() {
    FILENAME=$1
    PROCESS_LIMIT=$2
    CHKSTRING=`ps aux`
    CHKCOUNT=`echo "${CHKSTRING}" | grep -c ${FILENAME}`
    if [ ${CHKCOUNT} -gt ${PROCESS_LIMIT} ]; then
        echo "another ${FILENAME} is running, exit"
        exit
    fi
}
#end check_instance

#####################################################################################
##
## "main" procedure
##

## prevent the apup & apdown run in parallel, keep them run in sequence
check_instance /etc/ath/apup 1
check_instance /etc/ath/apdown 0

##force delay of 2 seconds 
##On peregrine environments we are seeing random crashes when apup and
##apdown are done immediate
sleep 2
MODLIST=`lsmod | cut -f1,0 -d" " | grep ath_hal`

if [ "${MODLIST}" = "ath_hal" ]; then
    echo "AP is already up"
    exit
fi

##
## Bring in the default environmental variables
##

. /etc/ath/apcfg

ifconfig br0 $AP_IPADDR netmask $AP_NETMASK up

WAN_IF=${WAN_IF:=WAN}
LAN_IF=${LAN_IF:=LAN}
HOSTAPD_VER=`hostapd -v 2>&1|grep hostapd|cut -f2 -d' '`

##
## For safety, delete all /tmp nodes we may re-create
##

rm -rf /tmp/br*
rm -rf /tmp/bc*
rm -rf /tmp/ap*
rm -rf /tmp/sta*
rm -rf /tmp/top*

if [ "${AP_CONF_ACFG}"  -eq "1" ]; then
	prepareACFG load
	exit 0
fi

##
## Determine the number of radios installed
##

NUMRADIO_AHB=${NUMRADIO_AHB:=0}
NUMRADIO_PCI=`grep -c 168c /proc/bus/pci/devices`
NUMRADIO=`expr ${NUMRADIO_PCI} + ${NUMRADIO_AHB}`

##
## Make sure the number is 1 or 2.  Any other is invalid
##

if [ $NUMRADIO -gt 2 -o $NUMRADIO -lt 1 ]; then
    echo "INVALID CONFIGURATION, RADIO NOT INSTALLED"
    exit 255
fi

if [ "${AP_STARTMODE}" = "dual" ]; then
    if [ $NUMRADIO = 1 ]; then
        AP_STARTMODE=standard
    else
        AP_STARTMODE=multi
    fi
fi

ap_modes="standard rootap extap repeater repeater-ind wrap"

for i in $ap_modes;
do
    if [ "${AP_STARTMODE}" = "${i}" ]; then
        cfg -a DEF_ATH_countrycode=841
    fi
done

##
## Now, process the modes
##

if [ "${AP_STARTMODE}" = "standard" ]; then
    makeVAP ap "$AP_SSID" $AP_RADIO_ID:$AP_RFPARAM
    if [ $? != 0 ]; then
        echo "Unable to create VAP!"
        exit
    fi
    activateVAP ath0:$AP_RADIO_ID br0 $AP_SECMODE $AP_SECFILE $WPS_ENABLE $WPS_VAP_TIE
fi

##
## See the activateVAP script for details on arguments.  Other configuration
## examples are as follows:
##

##
## Root AP for WDS
##

if [ "${AP_STARTMODE}" = "rootap" ]; then
    makeVAP ap-wds "$AP_SSID" $AP_RADIO_ID:$AP_RFPARAM
    if [ $? != 0 ]; then
        echo "Unable to create VAP!"
        exit
    fi

    activateVAP ath0:$AP_RADIO_ID br0 $AP_SECMODE $AP_SECFILE  $WPS_ENABLE
fi
##
## REPEATER
##
## In repeater mode, VAP 1 (ath0) is ALWAYS the AP side, and VAP 2 (ath1) is
## ALWAYS the client side.  Thus, if ROOTAP_MAC needs to be defined, it's for
## VAP 2 and should be ROOTAP_MAC_2.
##
## If ANY OTHER CONFIGURATION is required, then set AP_STARTMODE=multi and
## set the specific VAP configurations as required.
##

if [ "${AP_STARTMODE}" = "repeater" -o "${AP_STARTMODE}" = "repeater-ind" ]; then
    if [ "${AP_STARTMODE}" = "repeater" ]; then
        APMODE="ap-wds"
        STAMODE="sta-wds"
    else
        APMODE="ap-wds-ind"
        STAMODE="sta-wds-ind"
    fi
    makeVAP ${APMODE} "$AP_SSID" $AP_RADIO_ID:$AP_RFPARAM
    if [ $? != 0 ]; then
        echo "Unable to create VAP!"
        exit
    fi
    makeVAP ${STAMODE} "$AP_SSID_2" $AP_RADIO_ID_2:$AP_RFPARAM_2
    if [ $? != 0 ]; then
        echo "Unable to create VAP!"
        exit
    fi

## Disable RADAR for AP vap's phy interface(wifiX) in WDS repeater mode
    if [ "${AP_STARTMODE}" = "repeater" ]; then
        radartool -i wifi$AP_RADIO_ID disable
    fi

    if [ "${ROOTAP_MAC_2}" != "" ]; then
        iwconfig ath1 ap $ROOTAP_MAC_2
    fi
    if [ "${AP_STARTMODE}" = "repeater-ind" ]; then
        activateVAP ath0:$AP_RADIO_ID br0 $AP_SECMODE $AP_SECFILE $WPS_ENABLE
        activateVAP ath1:$AP_RADIO_ID_2 br0 $AP_SECMODE_2 $AP_SECFILE_2 $WPS_ENABLE_2
    else
        activateVAP ath1:$AP_RADIO_ID_2 br0 $AP_SECMODE_2 $AP_SECFILE_2 $WPS_ENABLE_2
        activateVAP ath0:$AP_RADIO_ID br0 $AP_SECMODE $AP_SECFILE $WPS_ENABLE
    fi
fi

## Extender AP
##
if [ "${AP_STARTMODE}" = "extap" ]; then
    makeVAP ap "$AP_SSID" $AP_RADIO_ID:$AP_RFPARAM 
    if [ $? != 0 ]; then
        echo "Unable to create VAP!"
        exit
    fi

    AP_SSID_2=${AP_SSID_2:=$AP_SSID}
    ROOTAP_SSID=${ROOTAP_SSID:=$AP_SSID_2}

    if [ "${ROOTAP_SSID}" = "any" -a  "${ROOTAP_MAC}" = "" ]; then
        echo "ROOTAP_MAC should be set if ROOTAP_SSID=any"
        exit 1
    else
        makeVAP sta-ext "$AP_SSID_2" $AP_RADIO_ID_2:$AP_RFPARAM_2
    fi

    if [ "${ROOTAP_MAC}" != "" ]; then
        iwconfig ath1 ap $ROOTAP_MAC
    fi

    activateVAP ath1:$AP_RADIO_ID_2 br0 $AP_SECMODE_2 $AP_SECFILE_2 $WPS_ENABLE_2
    activateVAP ath0:$AP_RADIO_ID br0 $AP_SECMODE $AP_SECFILE $WPS_ENABLE
fi

##
## Extender STA
##
if [ "${AP_STARTMODE}" = "extsta" ]; then

    ROOTAP_SSID=${ROOTAP_SSID:=$AP_SSID}

    if [ "${ROOTAP_SSID}" = "any" -a  "${ROOTAP_MAC}" = "" ]; then
        echo "ROOTAP_MAC should be set if ROOTAP_SSID=any"
        exit 1
    else
        makeVAP sta-ext-sin "$ROOTAP_SSID" $AP_RADIO_ID:$AP_RFPARAM
    fi

    if [ "${ROOTAP_MAC}" != "" ]; then
        iwconfig ath0 ap $ROOTAP_MAC
    fi

    activateVAP ath0:$AP_RADIO_ID br0 $AP_SECMODE $AP_SECFILE $WPS_ENABLE
fi

##
## "VIRTUAL WIRE" client
##
if [ "${AP_STARTMODE}" = "client" ]; then
    makeVAP sta-wds "$AP_SSID" $AP_RADIO_ID:$AP_RFPARAM
    if [ $? != 0 ]; then
        echo "Unable to create VAP!"
        exit
    fi

    if [ "${ROOTAP_MAC}" != "" ]; then
        iwconfig ath0 ap $ROOTAP_MAC
    fi

    activateVAP ath0:$AP_RADIO_ID br0 $AP_SECMODE $AP_SECFILE $WPS_ENABLE
fi


##
## STATION FORWARDING
##
if [ "${AP_STARTMODE}" = "stafwd" ]; then
    makeVAP sta-fwd-sin "$AP_SSID" $AP_RADIO_ID:$AP_RFPARAM
    if [ $? != 0 ]; then
        echo "Unable to create VAP!"
        exit
    fi

    activateVAP ath0:$AP_RADIO_ID br0 $AP_SECMODE $AP_SECFILE $WPS_ENABLE
fi

##
## mBSSID case with all types of authentication
## Note that WEP MUST be the first VAP
## This is brute force, but effective.  Note that we set the becon interval
## to 400
##

WEP_INTERFACE=0
if [ "${AP_STARTMODE}" = "multi" -o "${AP_STARTMODE}" = "multi-ind" ]; then
    NUM_VAP=0
    #Note: Below variable used later in script. Do not over-write after
    #final computation in loop
    VAP_COUNT_RADIO_0=0
    VAP_COUNT_RADIO_1=0
    STA_VAP_COUNT_RADIO_0=0
    STA_VAP_COUNT_RADIO_1=0
    for i in $my_vaps;
    do
        ITER_SSID="AP_SSID$i"
        ITER_MODE="AP_MODE$i"
        ITER_SECMODE="AP_SECMODE$i"
        ITER_RFPARAM="AP_RFPARAM$i"
        ITER_RADIO_ID="AP_RADIO_ID$i"
        ITER_ROOTAP_MAC="ROOTAP_MAC$i"
        VAP_NAME="ath$NUM_VAP"
        eval ITER_SSID=\$$ITER_SSID
        eval ITER_MODE=\$$ITER_MODE
        eval ITER_SECMODE=\$$ITER_SECMODE
        eval ITER_RFPARAM=\$$ITER_RFPARAM
        eval ITER_RADIO_ID=\$$ITER_RADIO_ID
        eval ITER_ROOTAP_MAC=\$$ITER_ROOTAP_MAC
        if [ "x${ITER_SSID}" != "x" ]; then
            VAP_COUNT_VAR="VAP_COUNT_RADIO_$ITER_RADIO_ID"
            eval ITER_VAP_COUNT=\$$VAP_COUNT_VAR
            ITER_VAP_COUNT=$(($ITER_VAP_COUNT+1))
            export $VAP_COUNT_VAR=$ITER_VAP_COUNT
            if [ "$VAP_COUNT_RADIO_0" -gt "$MAX_VAPS_PER_RADIO" -o "$VAP_COUNT_RADIO_1" -gt "$MAX_VAPS_PER_RADIO" ]; then
                echo "Exceeded max VAPs per Radio($MAX_VAPS_PER_RADIO)"
                exit 255
            fi
            if [ "${ITER_SECMODE}" = "WEP" -a "${WEP_MBSSID}" != 1 ]; then
                echo $WEP_INTERFACE | grep "R${ITER_RADIO_ID}" > /dev/null
                if [ $? -eq 0 ]; then
                    echo "Unable to create additional WEP VAP"
                    exit 255
                else
                    WEP_INTERFACE="R${ITER_RADIO_ID}"
                fi
            fi
            BEACON_INTVAL=$((100*$ITER_VAP_COUNT))
      
            if [ "${ITER_MODE}" = "ap-wds" -o "${ITER_MODE}" = "ap" ]; then
                if [ "${ITER_RADIO_ID}" = 0 ]; then
                    cfg -a DEF_ATH_countrycode=841
                else
                    cfg -a DEF_ATH_countrycode_2=841
                fi
            fi
      
            if [ "${ITER_MODE}" = "sta-wds" -o "${ITER_MODE}" = "sta" ]; then
               if [ "${ITER_RADIO_ID}" = 0 -a "${STA_VAP_COUNT_RADIO_0}" != 1 ]; then
                 if [ "${AP_STARTMODE}" = "multi-ind" ]; then
                    if [ "${ITER_MODE}" = "sta-wds" ]; then
                      ST_MODE="sta-wds-ind"
                    else
                      ST_MODE="sta-nwds-ind"
                    fi
                    makeVAP $ST_MODE "$ITER_SSID" $ITER_RADIO_ID:$ITER_RFPARAM $BEACON_INTVAL
                 else
                    makeVAP $ITER_MODE "$ITER_SSID" $ITER_RADIO_ID:$ITER_RFPARAM $BEACON_INTVAL
                 fi
                    NUM_VAP=$(($NUM_VAP+1))
		    iwconfig | grep -c ath | grep -i $NUM_VAP > /dev/null               
		    if [ $? != 0 ]; then
		           echo "Unable to create VAP!"
		    	   exit
	            fi
	            STA_VAP_COUNT_RADIO_0=1
                else if [ "${ITER_RADIO_ID}" = 1 -a "${STA_VAP_COUNT_RADIO_1}" != 1 ]; then
                    if [ "${AP_STARTMODE}" = "multi-ind" ]; then
                      if [ "${ITER_MODE}" = "sta-wds" ]; then
                        ST_MODE="sta-wds-ind"
                      else
                        ST_MODE="sta-nwds-ind"
                      fi
                       makeVAP $ST_MODE "$ITER_SSID" $ITER_RADIO_ID:$ITER_RFPARAM $BEACON_INTVAL
                    else
		       makeVAP $ITER_MODE "$ITER_SSID" $ITER_RADIO_ID:$ITER_RFPARAM $BEACON_INTVAL
                    fi
		      NUM_VAP=$(($NUM_VAP+1))
		      iwconfig | grep -c ath | grep -i $NUM_VAP > /dev/null               
		      if [ $? != 0 ]; then
		              echo "Unable to create VAP!"
		      	      exit
	              fi
	              STA_VAP_COUNT_RADIO_1=1
	         else
	            echo "**Maximum sta / sta-wds VAPs exceeded!!!!"
		 fi
	     fi
            else       
              if [ "${AP_STARTMODE}" = "multi-ind" ]; then
                 if [ "${ITER_MODE}" = "ap-wds" ]; then
                     AP_IN_MODE="ap-wds-ind"
                 else
                     AP_IN_MODE="ap-nwds-ind"
                 fi
                  makeVAP $AP_IN_MODE "$ITER_SSID" $ITER_RADIO_ID:$ITER_RFPARAM $BEACON_INTVAL
              else
                  makeVAP $ITER_MODE "$ITER_SSID" $ITER_RADIO_ID:$ITER_RFPARAM $BEACON_INTVAL
              fi
                 NUM_VAP=$(($NUM_VAP+1))
	         iwconfig | grep -c ath | grep -i $NUM_VAP > /dev/null               
	         if [ $? != 0 ]; then
	                  echo "Unable to create VAP!"
	                  exit
	         fi
            fi 
        fi
        if [ "${ITER_MODE}" = "sta-wds" -a "${ITER_SECMODE}" != "WPA" -a "${ITER_ROOTAP_MAC}" != "" ]; then
            iwconfig $VAP_NAME ap $ITER_ROOTAP_MAC
        fi
    done

    VAP_NUM=0
    STA_VAP_COUNT_RADIO_0=0
    STA_VAP_COUNT_RADIO_1=0
    for i in $my_vaps;
    do
        ITER_SSID="AP_SSID$i"
        ITER_RADIO_ID="AP_RADIO_ID$i"
        ITER_SECMODE="AP_SECMODE$i"
        ITER_SECFILE="AP_SECFILE$i"
        ITER_WPS_ENABLE="WPS_ENABLE$i"
        ITER_WPS_VAP_TIE="WPS_VAP_TIE$i"
        eval ITER_SSID=\$$ITER_SSID
        eval ITER_RADIO_ID=\$$ITER_RADIO_ID
        eval ITER_SECMODE=\$$ITER_SECMODE
        eval ITER_SECFILE=\$$ITER_SECFILE
        eval ITER_WPS_ENABLE=\$$ITER_WPS_ENABLE
        eval ITER_WPS_VAP_TIE=\$$ITER_WPS_VAP_TIE
        if [ "${ITER_MODE}" = "sta-wds" -o "${ITER_MODE}" = "sta" ]; then
         if [ "${ITER_RADIO_ID}" = 0 ]; then
           if [ "${STA_VAP_COUNT_RADIO_0}" != 1 ]; then
             if [ "_${ITER_SSID}" != "_" ]; then
               activateVAP ath$VAP_NUM:$ITER_RADIO_ID br0 $ITER_SECMODE $ITER_SECFILE $ITER_WPS_ENABLE $ITER_WPS_VAP_TIE
               VAP_NUM=$(($VAP_NUM+1))
               STA_VAP_COUNT_RADIO_0=1
             fi
           fi
         else
           if [ "${STA_VAP_COUNT_RADIO_1}" != 1 ]; then
	     if [ "_${ITER_SSID}" != "_" ]; then
	       activateVAP ath$VAP_NUM:$ITER_RADIO_ID br0 $ITER_SECMODE $ITER_SECFILE $ITER_WPS_ENABLE $ITER_WPS_VAP_TIE
	       VAP_NUM=$(($VAP_NUM+1))
	       STA_VAP_COUNT_RADIO_1=1
	      fi
           fi
          fi
         else
           if [ "_${ITER_SSID}" != "_" ]; then
                 activateVAP ath$VAP_NUM:$ITER_RADIO_ID br0 $ITER_SECMODE $ITER_SECFILE $ITER_WPS_ENABLE $ITER_WPS_VAP_TIE
                 VAP_NUM=$(($VAP_NUM+1))
            fi
         fi
    done
fi

if [ "${AP_STARTMODE}" = "multivlan" -o "${AP_STARTMODE}" = "multivlan-ind" ]; then
    WEP_INTERFACE="" 
    NUM_VAP=0
    #Note: Below variable used later in script. Do not over-write after
    #final computation in loop
    VAP_COUNT_RADIO_0=0
    VAP_COUNT_RADIO_1=0
    STA_VAP_COUNT_RADIO_0=0
    STA_VAP_COUNT_RADIO_1=0
    for i in $my_vaps;
    do
        ITER_SSID="AP_SSID$i"
        ITER_MODE="AP_MODE$i"
        ITER_SECMODE="AP_SECMODE$i"
        ITER_RFPARAM="AP_RFPARAM$i"
        ITER_RADIO_ID="AP_RADIO_ID$i"
        ITER_ROOTAP_MAC="ROOTAP_MAC$i"
        VAP_NAME="ath$NUM_VAP"
        eval ITER_SSID=\$$ITER_SSID
        eval ITER_MODE=\$$ITER_MODE
        eval ITER_SECMODE=\$$ITER_SECMODE
        eval ITER_RFPARAM=\$$ITER_RFPARAM
        eval ITER_RADIO_ID=\$$ITER_RADIO_ID
        eval ITER_ROOTAP_MAC=\$$ITER_ROOTAP_MAC
        if [ "_${ITER_SSID}" != "_" ]; then
            VAP_COUNT_VAR="VAP_COUNT_RADIO_$ITER_RADIO_ID"
            eval ITER_VAP_COUNT=\$$VAP_COUNT_VAR
            ITER_VAP_COUNT=$(($ITER_VAP_COUNT+1))
            export $VAP_COUNT_VAR=$ITER_VAP_COUNT
            if [ "$VAP_COUNT_RADIO_0" -gt "$MAX_VAPS_PER_RADIO" -o "$VAP_COUNT_RADIO_1" -gt "$MAX_VAPS_PER_RADIO" ]; then
                echo "Exceeded max VAPs per Radio($MAX_VAPS_PER_RADIO)"
                exit 255
            fi
            if [ "${ITER_SECMODE}" = "WEP" -a "${WEP_MBSSID}" != 1]; then
                echo $WEP_INTERFACE | grep "R${ITER_RADIO_ID}" > /dev/null
                if [ $? -eq 0 ]; then
                    echo "Unable to create additional WEP VAP"
                    exit 255
                else
                    WEP_INTERFACE="${WEP_INTERFACE}:R${ITER_RADIO_ID}"
                fi
            fi
            BEACON_INTVAL=$((100*$ITER_VAP_COUNT))

            if [ "${ITER_MODE}" = "ap-wds" -o "${ITER_MODE}" = "ap" ]; then
                if [ "${ITER_RADIO_ID}" = 0 ]; then
                   cfg -a  DEF_ATH_countrycode=841
                else 
                   cfg -a  DEF_ATH_countrycode_2=841
                fi
            fi

            if [ "${ITER_MODE}" = "sta-wds" -o "${ITER_MODE}" = "sta" ]; then
	        if [ "${ITER_RADIO_ID}" = 0 -a "${STA_VAP_COUNT_RADIO_0}" != 1 ]; then
                  if [ "${AP_STARTMODE}" = "multivlan-ind" ]; then
                    if [ "{$ITER_MODE}" = "sta-wds" ]; then
                      ST_MODE="sta-wds-ind"
                    else
                      ST_MODE="sta-nwds-ind"
                    fi  
                     makeVAP $ST_MODE "$ITER_SSID" $ITER_RADIO_ID:$ITER_RFPARAM $BEACON_INTVAL
                  else
	             makeVAP $ITER_MODE "$ITER_SSID" $ITER_RADIO_ID:$ITER_RFPARAM $BEACON_INTVAL
                  fi
	           NUM_VAP=$(($NUM_VAP+1))
	    	   iwconfig | grep -c ath | grep -i $NUM_VAP > /dev/null               
	    	   if [ $? != 0 ]; then
	    	          echo "Unable to create VAP!"
	    	   	   exit
	    	    fi
	    	    STA_VAP_COUNT_RADIO_0=1
	         else if [ "${ITER_RADIO_ID}" = 1 -a "${STA_VAP_COUNT_RADIO_1}" != 1 ]; then
                   if [ "${AP_STARTMODE}" = "multivlan-ind" ]; then
                     if [ "${ITER_MODE}" = "sta-wds" ]; then
                       ST_MODE="sta-wds-ind"
                     else
                       ST_MODE="sta-nwds-ind"
                     fi
                      makeVAP $ST_MODE "$ITER_SSID" $ITER_RADIO_ID:$ITER_RFPARAM $BEACON_INTVAL
                   else
	    	      makeVAP $ITER_MODE "$ITER_SSID" $ITER_RADIO_ID:$ITER_RFPARAM $BEACON_INTVAL
                   fi
	    	    NUM_VAP=$(($NUM_VAP+1))
	    	    iwconfig | grep -c ath | grep -i $NUM_VAP > /dev/null               
	    	    if [ $? != 0 ]; then
	    	            echo "Unable to create VAP!"
	    	       	    exit
	    	    fi
	    	       STA_VAP_COUNT_RADIO_1=1
	    	  else
	    	         echo "**Maximum sta / sta-wds VAPs exceeded!!!!"
	    	  fi
	    	fi
	      else       
                if [ "${AP_STARTMODE}" = "multivlan-ind" ]; then
                  if [ "${ITER_MODE}" = "ap-wds" ]; then
                    AP_IN_MODE="ap-wds-ind"
                  else
                    AP_IN_MODE="ap-nwds-ind"
                  fi
                   makeVAP $AP_IN_MODE "$ITER_SSID" $ITER_RADIO_ID:$ITER_RFPARAM $BEACON_INTVAL
                else
	           makeVAP $ITER_MODE "$ITER_SSID" $ITER_RADIO_ID:$ITER_RFPARAM $BEACON_INTVAL
                fi
	           NUM_VAP=$(($NUM_VAP+1))
	    	   iwconfig | grep -c ath | grep -i $NUM_VAP > /dev/null               
	    	   if [ $? != 0 ]; then
	    	         echo "Unable to create VAP!"
	    	         exit
	    	   fi
              fi   
        fi
        if [ "${ITER_MODE}" = "sta-wds" -a "${ITER_SECMODE}" != "WPA" -a "${ITER_ROOTAP_MAC}" != "" ]; then
            iwconfig $VAP_NAME ap $ITER_ROOTAP_MAC
        fi
    done

    VAP_NUM=0
    STA_VAP_COUNT_RADIO_0=0
    STA_VAP_COUNT_RADIO_1=0
    for i in $my_vaps;
    do
        ITER_SSID="AP_SSID$i"
        ITER_RADIO_ID="AP_RADIO_ID$i"
        ITER_SECMODE="AP_SECMODE$i"
        ITER_SECFILE="AP_SECFILE$i"
        ITER_WPS_ENABLE="WPS_ENABLE$i"
        ITER_WPS_VAP_TIE="WPS_VAP_TIE$i"
        ITER_AP_BRNAME="AP_BRNAME$i"
        eval ITER_SSID=\$$ITER_SSID
        eval ITER_RADIO_ID=\$$ITER_RADIO_ID
        eval ITER_SECMODE=\$$ITER_SECMODE
        eval ITER_SECFILE=\$$ITER_SECFILE
        eval ITER_WPS_ENABLE=\$$ITER_WPS_ENABLE
        eval ITER_WPS_VAP_TIE=\$$ITER_WPS_VAP_TIE
        eval ITER_AP_BRNAME=\$$ITER_AP_BRNAME
        if [ "${ITER_MODE}" = "sta-wds" -o "${ITER_MODE}" = "sta" ]; then
	    if [ "${ITER_RADIO_ID}" = 0 ]; then
	       if [ "${STA_VAP_COUNT_RADIO_0}" != 1 ]; then
	         if [ "_${ITER_SSID}" != "_" ]; then
	            activateVAP ath$VAP_NUM:$ITER_RADIO_ID $ITER_AP_BRNAME $ITER_SECMODE $ITER_SECFILE $ITER_WPS_ENABLE $ITER_WPS_VAP_TIE
	            VAP_NUM=$(($VAP_NUM+1))
	            STA_VAP_COUNT_RADIO_0=1
	         fi
	      fi
	  else
	     if [ "${STA_VAP_COUNT_RADIO_1}" != 1 ]; then
	       if [ "_${ITER_SSID}" != "_" ]; then
		   activateVAP ath$VAP_NUM:$ITER_RADIO_ID $ITER_AP_BRNAME $ITER_SECMODE $ITER_SECFILE $ITER_WPS_ENABLE $ITER_WPS_VAP_TIE
		   VAP_NUM=$(($VAP_NUM+1))
		   STA_VAP_COUNT_RADIO_1=1
		fi
	       fi
	     fi
	    else
	      if [ "_${ITER_SSID}" != "_" ]; then
	         activateVAP ath$VAP_NUM:$ITER_RADIO_ID $ITER_AP_BRNAME $ITER_SECMODE $ITER_SECFILE $ITER_WPS_ENABLE $ITER_WPS_VAP_TIE
	         VAP_NUM=$(($VAP_NUM+1))
	      fi
          fi
    done

#configure VLANS and bridges
    brctl delif br0 ${WAN_IF}
    brctl delif br0 ${LAN_IF}
    ifconfig br0 0.0.0.0 up
    if [ "${AP_AUTHIF}" = "WAN" ]; then
            ifconfig ${WAN_IF} $AP_IPADDR up
    else
            ifconfig ${LAN_IF} $AP_IPADDR up
    fi

#
#vlan ids must be choosen. This is to provide better control on number of vaps need to be created.
#
    VAP_NUM=0
    for i in $my_vaps;
    do
        ITER_SSID="AP_SSID$i"
        ITER_VLAN="AP_VLAN$i"
        ITER_BRNAME="AP_BRNAME$i"
        ITER_SECMODE="AP_SECMODE$i"
        ITER_SECFILE="AP_SECFILE$i"
        ITER_VIPADDR="AP_VIPADDR$i"
        eval ITER_SSID=\$$ITER_SSID
        eval ITER_VLAN=\$$ITER_VLAN
        eval ITER_BRNAME=\$$ITER_BRNAME
        eval ITER_SECMODE=\$$ITER_SECMODE
        eval ITER_SECFILE=\$$ITER_SECFILE
        eval ITER_VIPADDR=\$$ITER_VIPADDR

        if [ "_${ITER_BRNAME}" = "_" ]; then
            ITER_BRNAME=br${ITER_VLAN}
        fi
        if [ "_${ITER_VLAN}" != "_" ]; then
            configure_vlanvap ath$VAP_NUM ${ITER_BRNAME:="br2"} ${ITER_VLAN} ${ITER_SECMODE:="None"} ${ITER_SECFILE:="None"} ${ITER_VIPADDR}
        fi
        if [ "_${ITER_SSID}" != "_" ]; then
            VAP_NUM=$(($VAP_NUM+1))
        fi
    done
fi

##
## IBSS MODE
##
if [ "${AP_STARTMODE}" = "adhoc" ]; then
    makeVAP adhoc "$IBSS_SSID" $AP_RADIO_ID:$AP_RFPARAM
    if [ $? != 0 ]; then
        echo "Unable to create VAP!"
        exit
    fi

    activateVAP ath0:$AP_RADIO_ID br0 $AP_SECMODE $AP_SECFILE
    brctl delif br0 ath0
fi

##
## WRAP (Wireless Repeater AP) MODE
##
if [ "${AP_STARTMODE}" = "wrap" ]; then
    # bring up the WRAP VAP
    makeVAP wrap "$AP_SSID" $AP_RADIO_ID:$AP_RFPARAM
    if [ $? != 0 ]; then
        echo "Unable to create WRAP VAP!"
        exit
    fi
    activateVAP ath0:$AP_RADIO_ID br0 $AP_SECMODE $AP_SECFILE $WPS_ENABLE $WPS_VAP_TIE
    if [ "${AP_ISOLATION}" = "1" ]; then
        echo "1 1" > /proc/wrap
        iwpriv ath0 ap_bridge 0
        ISO="-I"
    else
        ISO=""
    fi
    # set ath0 port flag WRAP_PTYPE_VAP
    brctl delif br0 ath0
    brctl addif br0 ath0 4097

    # bring up the main ProxySTA VAP
    makeVAP sta-proxy "any" $AP_RADIO_ID:$AP_RFPARAM
    if [ $? != 0 ]; then
        echo "Unable to create main ProxySTA VAP!"
        exit
    fi
    activateVAP ath1:$AP_RADIO_ID none $AP_SECMODE $AP_SECFILE $WPS_ENABLE $WPS_VAP_TIE
    if [ ${WPS_ENABLE} -ne 0 ]; then
        WPASCONF=/etc/wpa2/WSC_sta.conf
    else
        WPASCONF=/tmp/supath1
    fi
    # set ath1 port flag WRAP_PTYPE_MPVAP
    brctl delif br0 ath1
    brctl addif br0 ath1 4101

    # set the br0 MAC address the same as ath1
    ifconfig br0 hw ether `ifconfig ath1 |grep HWaddr |cut -d 'r' -f 3`

    # set WAN port flag WRAP_PTYPE_ETH
    brctl delif br0 WAN
    brctl addif br0 WAN 4096
    brctl addif br0 LAN 4096

    wpa_supplicant -B -g/var/run/wpa_supplicant-global -bbr0
fi

##
## WRAP (Wireless Repeater AP) MODE WIRED ONLY SUPPORT
##
if [ "${AP_STARTMODE}" = "wrap-wired" ]; then

    if [ "${AP_ISOLATION}" = "1" ]; then
        echo "1 1" > /proc/wrap
        iwpriv ath0 ap_bridge 0
        ISO="-I"
    else
        ISO=""
    fi

    # bring up the main ProxySTA VAP
    makeVAP sta-proxy "any" $AP_RADIO_ID:$AP_RFPARAM
    if [ $? != 0 ]; then
        echo "Unable to create main ProxySTA VAP!"
        exit
    fi
    activateVAP ath0:$AP_RADIO_ID none $AP_SECMODE $AP_SECFILE $WPS_ENABLE $WPS_VAP_TIE
    if [ ${WPS_ENABLE} -ne 0 ]; then
        WPASCONF=/etc/wpa2/WSC_sta.conf
    else
        WPASCONF=/tmp/supath0
    fi
    # set ath1 port flag WRAP_PTYPE_MPVAP
    brctl delif br0 ath0
    brctl addif br0 ath0 4101

    # set the br0 MAC address the same as ath1
    ifconfig br0 hw ether `ifconfig ath0 |grep HWaddr |cut -d 'r' -f 3`

    # set WAN port flag WRAP_PTYPE_ETH
    brctl delif br0 WAN
    brctl addif br0 WAN 4096
    brctl addif br0 LAN 4096

    wpa_supplicant -B -g/var/run/wpa_supplicant-global -bbr0
fi

##
## WRAP (Wireless Repeater AP) MODE
##
if [ "${AP_STARTMODE}" = "wrap-dbdc" ]; then 	
    # bring up the WRAP VAP
    makeVAP ap "$AP_SSID" $AP_RADIO_ID:$AP_RFPARAM
    if [ $? != 0 ]; then
        echo "Unable to create WRAP VAP!"
        exit
    fi

    activateVAP ath0:$AP_RADIO_ID br0 $AP_SECMODE $AP_SECFILE $WPS_ENABLE $WPS_VAP_TIE
    if [ "${AP_ISOLATION}" = "1" ]; then
        echo "1 1" > /proc/wrap
        iwpriv ath0 ap_bridge 0
        ISO="-I"
    else
        ISO=""
    fi
    
    # set ath0 port flag WRAP_PTYPE_VAP
    brctl delif br0 ath0
    brctl addif br0 ath0 4097

    # bring up the main ProxySTA VAP
    makeVAP sta-proxy "any" $AP_RADIO_ID_2:$AP_RFPARAM_2
    if [ $? != 0 ]; then
        echo "Unable to create main ProxySTA VAP!"
        exit
    fi
    
    activateVAP ath1:$AP_RADIO_ID_2 none $AP_SECMODE $AP_SECFILE $WPS_ENABLE $WPS_VAP_TIE
    if [ ${WPS_ENABLE} -ne 0 ]; then
        WPASCONF=/etc/wpa2/WSC_sta.conf
    else
        WPASCONF=/tmp/supath1
    fi

    # set ath1 port flag WRAP_PTYPE_MPVAP
    brctl delif br0 ath1
    brctl addif br0 ath1 4101

    # set the br0 MAC address the same as ath1
    ifconfig br0 hw ether `ifconfig ath1 |grep HWaddr |cut -d 'r' -f 3`

    # set WAN port flag WRAP_PTYPE_ETH
    brctl delif br0 WAN
    brctl addif br0 WAN 4096
    brctl addif br0 LAN 4096

    wpa_supplicant -B -g/var/run/wpa_supplicant-global -bbr0
fi

##############


##############

echo "CHH: System Configuration"
cfg -s

##############

unset IS_WPA
unset IS_WPS

IS_WPA=`set | grep WPA`
IS_WPS=`set | grep "WPS_ENABLE" | grep 1`

##
## Now, make the topology file
##

if [ "${IS_WPA}" != "" -o "${IS_WPS}" != "" ]; then
    if [ "${HOSTAPD_VER}" = "v0.5.9" ]; then
    echo "Making Topology File . . ."
    # for vlan case we should not be adding br0 
    if [ -f /tmp/br0 ] && [ "${AP_STARTMODE}" != "multivlan" ]; then
        echo -e "bridge br0" > /tmp/topology.conf
        echo -e "{" >> /tmp/topology.conf
        echo -e "\tipaddress ${AP_IPADDR}" >> /tmp/topology.conf
        echo -e "\tipmask ${AP_NETMASK}" >> /tmp/topology.conf
        cat /tmp/br0 >> /tmp/topology.conf
        echo -e "\tinterface WAN" >> /tmp/topology.conf
        echo -e "\tinterface LAN" >> /tmp/topology.conf
        echo -e "}" >> /tmp/topology.conf
    else
        echo "bridge none" > /tmp/topology.conf
        echo "{" >> /tmp/topology.conf
        echo "}" >> /tmp/topology.conf
    fi

    ##
    ## Assume up to 8 vlan specifications
    ##
    for i in $my_vaps;
    do
        ITER_VLAN="AP_VLAN$i"
        ITER_BRNAME="AP_BRNAME$i"
        eval ITER_VLAN=\$$ITER_VLAN
        eval ITER_BRNAME=\$$ITER_BRNAME
        if [ -f /tmp/bc${ITER_VLAN} ]; then
            echo -e "bridge ${ITER_BRNAME}" >> /tmp/topology.conf
            echo -e "{" >> /tmp/topology.conf
            echo -e "\tinterface WAN.${ITER_VLAN}" >> /tmp/topology.conf
            echo -e "\tinterface LAN.${ITER_VLAN}" >> /tmp/topology.conf
            cat /tmp/bc${ITER_VLAN} >> /tmp/topology.conf
            echo -e "}" >> /tmp/topology.conf
            #when the file is processed rename it with .done, so that we
            #do not process it again. This should help when we have same
            #vlan for all the vaps in mbssid
            mv /tmp/bc${ITER_VLAN} /tmp/bc${ITER_VLAN}.done
        fi
    done

    if [ -f /tmp/aplist0 -o -f /tmp/stalist0 ]; then
        echo "radio wifi0" >> /tmp/topology.conf
        echo "{" >> /tmp/topology.conf

        if [ -f /tmp/aplist0 ]; then
            echo -e "\tap" >> /tmp/topology.conf
            echo -e "\t{" >> /tmp/topology.conf
            cat /tmp/aplist0 >> /tmp/topology.conf
            echo -e "\t}" >> /tmp/topology.conf
        fi

        if [ -f /tmp/stalist0 ]; then
            cat /tmp/stalist0 >> /tmp/topology.conf
        fi

        echo "}" >> /tmp/topology.conf
    fi

    if [ -f /tmp/aplist1 -o -f /tmp/stalist1 ]; then
        echo "radio wifi1" >> /tmp/topology.conf
        echo "{" >> /tmp/topology.conf
        
        if [ -f /tmp/aplist1 ]; then
            echo -e "\tap" >> /tmp/topology.conf
            echo -e "\t{" >> /tmp/topology.conf
            cat /tmp/aplist1 >> /tmp/topology.conf
            echo -e "\t}" >> /tmp/topology.conf
        fi

        if [ -f /tmp/stalist1 ]; then
            cat /tmp/stalist1 >> /tmp/topology.conf
        fi
        echo "}" >> /tmp/topology.conf
    fi

    #
    # Start hostapd & wsc_supplicant.  Check for the
    # appropriate file lists to determine if they need
    # to be started . . .
    #
    # Note that /var/run is statically linked to /tmp . . .
    #

    if [ -f /tmp/aplist0 -o -f /tmp/aplist1 ]; then
        hostapd /var/run/topology.conf &
    fi
    if [ -f /tmp/stalist0 -o -f /tmp/stalist1 ]; then
        sleep 2
        wpa_supplicant /var/run/topology.conf &
    fi
    else
	if [ -f /tmp/conf_filename ]; then
            hostapd  -B `cat /tmp/conf_filename` -e /etc/wpa2/entropy
	fi
	if [ -f /tmp/sta_conf_filename ]; then
            if [ "${AP_STARTMODE}" = "wrap" -o "${AP_STARTMODE}" = "wrap-dbdc" ]; then
                wpa_supplicant -B -W `cat /tmp/sta_conf_filename`
            else
                wpa_supplicant `cat /tmp/sta_conf_filename` &
            fi
	fi
    fi
fi

if [ "${AP_STARTMODE}" = "wrap" ]; then
    # start wrapd to detect and configure new wireless clients automatically
    if [ -f /tmp/conf_filename ]; then
        IFACE="-a ath0"
    fi
    wrapd ${ISO} -c${WPASCONF} ${IFACE} -p ath1 -v /etc/ath/wrap-vma.txt -g /var/run/wrapd-global -w/var/run/wpa_supplicant-global &
fi

if [ "${AP_STARTMODE}" = "wrap-wired" ]; then
    # start wrapd to detect and configure new wireless clients automatically
    wrapd ${ISO} -c${WPASCONF} ${IFACE} -p ath0 -v /etc/ath/wrap-vma.txt -g /var/run/wrapd-global -w/var/run/wpa_supplicant-global &
fi

if [ "${AP_STARTMODE}" = "wrap-dbdc" ]; then
    # start wrapd to detect and configure new wireless clients automatically
 
    if [ -f /tmp/conf_filename ]; then
        IFACE="-a ath0"
    fi
    wrapd ${ISO} -c${WPASCONF} ${IFACE} -p ath1 -d wifi$AP_RADIO_ID_2 -v /etc/ath/wrap-vma.txt -g /var/run/wrapd-global -w/var/run/wpa_supplicant-global &
fi

#check if VoW need to be enabled
if [ "${VOW_ENABLE}" -eq "1" ]; then
    iwpriv wifi0 setVowExt 31
fi

if [ "${VOW_ENABLE_2}" -eq "1" ]; then
    iwpriv wifi1 setVowExt 31
fi

if [ "${ICM_ENABLE}" -eq "1" ]; then

    ## Determine mode to be used by icm:
    ## server (agent for external entity) or standalone (manage channel by itself).
    ## Create argument string accordingly.

    ## Default mode: standalone
    ICM_MODE_ARG=""

    if [ "${ICM_MODE}" = "server" ]; then
        ICM_MODE_ARG="-v"
    fi

    ## Create argument string for enabling/disabling daemon mode.
    ## Default: enabled
    ICM_DAEMON_ENABLE_ARG="-e"

    if [ "${ICM_DAEMON_ENABLE}" = "0" ]; then
        ICM_DAEMON_ENABLE_ARG=""
    fi

    ## Create argument string for enabling selection debug information dump
    ## Default: Whatever is set in icm.conf
    ICM_DEBUG_SELDEBUG_DUMP_ARG=""
    if [ "${ICM_ENABLE_SELDEBUG_DUMP}" -eq "1" ]; then
        ICM_DEBUG_SELDEBUG_DUMP_ARG="-i"
    fi

    ## Create argument string for setting debug level
    ## Default: Whatever is set in icm.conf
    ICM_DEBUG_LEVEL_ARG=""

    if [ -n "${ICM_DEBUG_LEVEL}" ]; then
       #The application carries out verification of debug level string
       ICM_DEBUG_LEVEL_ARG="-q ${ICM_DEBUG_LEVEL}";
    fi

    ## Create argument string for setting debug mask
    ## Default: Whatever is set in icm.conf
    ICM_DEBUG_MASK_ARG=""

    if [ -n "${ICM_DEBUG_MASK}" ]; then
        #The application carries out verification of debug mask string
        ICM_DEBUG_MASK_ARG="-u ${ICM_DEBUG_MASK}";
    fi

    #Currently, we support the below AP_STARTMODE values for ICM. More will be added in the future.
    if [ "${AP_STARTMODE}" = "standard" -o "${AP_STARTMODE}" = "rootap" -o "${AP_STARTMODE}" = "repeater" -o "${AP_STARTMODE}" = "dual" -o "${AP_STARTMODE}" = "multi" ]; then
        echo "Waiting for ${ICM_WAIT_TIME_IN_SECS} seconds for the device to settle"
        sleep ${ICM_WAIT_TIME_IN_SECS}
        icm $ICM_MODE_ARG $ICM_DAEMON_ENABLE_ARG $ICM_DEBUG_SELDEBUG_DUMP_ARG $ICM_DEBUG_LEVEL_ARG $ICM_DEBUG_MASK_ARG -f &
    else
        echo "Error: This AP_STARTMODE configuration is currently unsupported by ICM."
        echo "Supported configurations: standard, rootap, repeater, dual, multi."
        echo "Please restart with a supported configuration."
    fi
fi


