#
# Copyright (c) 2013 Qualcomm Atheros, Inc.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA. 
#

#ifndef HAVE_IF_INDEX
#COMPAT_SOURCES=  \
#	libbridge_compat.c
#else
#COMPAT_SOURCES=
#endif

LIBBRIDGE_SOURCES= \
	$(COMPAT_SOURCES) \
	libbridge_devif.c \
	libbridge_if.c \
	libbridge_init.c \
	libbridge_misc.c

lib-$(CONFIG_BRCTL):=$(LIBBRIDGE_SOURCES:.c=.o)
